name: Build Kernel-Next with GKI
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - name: Set swap
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 8

    - name: Setup build kernel environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Delhi date "+%y%m%d")" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install git dwarves libelf-dev ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3
        curl -so repo https://storage.googleapis.com/git-repo-downloads/repo
        sudo mv repo /usr/bin
        sudo chmod +x /usr/bin/repo
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
        sudo mkdir -p /mnt/kernel_workspace
        sudo chmod 0777 /mnt/kernel_workspace
        cd /mnt/kernel_workspace
        git clone https://github.com/izsdeaman97/GKI-Kernelsu-susfs --depth=1

    - name: Download source code
      run: |
        cd /mnt/kernel_workspace
        repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android14-6.1-2024-10
        repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast

    - name: KernelSU / SUSFS / Misc
      run: |
        cd /mnt/kernel_workspace
        echo "Add KernelSU"
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
          
    - name: Apply SUSFS Patches
      run: |
        echo "Changing to configuration directory: /mnt/kernel_workspace..."
        cd "/mnt/kernel_workspace"
        echo "Applying SUSFS patches..."
           
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
        cp /mnt/kernel_workspace/GKI-Kernelsu-susfs/patches/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./KernelSU-Next/
        cp /mnt/kernel_workspace/GKI-Kernelsu-susfs/patches/apk_sign.c_fix.patch ./KernelSU-Next/
        #cp /mnt/kernel_workspace/GKI-Kernelsu-susfs/patches/mksu_susfs.patch ./KernelSU/
        #cp /mnt/kernel_workspace/GKI-Kernelsu-susfs/patches/mksu.fix.patch ./KernelSU/
        cd KernelSU-Next
        patch -p1 < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
        patch -p1 < apk_sign.c_fix.patch || true
        #patch -p1 < mksu_susfs.patch || true
        #patch -p1 < mksu.fix.patch || true
        cd -
        echo "apply patch"
        cp /mnt/kernel_workspace/susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch /mnt/kernel_workspace/common/
        cp /mnt/kernel_workspace/GKI-Kernelsu-susfs/patches/syscall_hooks.patch /mnt/kernel_workspace/common/
        cp /mnt/kernel_workspace/susfs4ksu/kernel_patches/fs/* /mnt/kernel_workspace/common/fs/
        cp /mnt/kernel_workspace/susfs4ksu/kernel_patches/include/linux/* /mnt/kernel_workspace/common/include/linux/
        cd /mnt/kernel_workspace/common
        patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
        patch -p1 -F 3 < syscall_hooks.patch || true

    - name: Apply Hide Stuff Patches
      run: |
          # Apply additional patch
           cd /mnt/kernel_workspace/common
           cp /mnt/kernel_workspace/GKI-Kernelsu-susfs/patches/69_hide_stuff.patch /mnt/kernel_workspace/common/
           patch -p1 -F 3 < 69_hide_stuff.patch || true
    
        
    - name: Add Configuration Settings
      run: |
          echo "Changing to configuration directory: /mnt/kernel_workspace/"
          cd "/mnt/kernel_workspace"
        
          echo "Adding configuration settings to gki_defconfig..."
        
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_WITH_KPROBES=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig

          # Add additional tmpfs config setting
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig

          # Add additional config setting
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Hardcode Timestamp 
           sed -i -e 's|\$(preempt-flag-y) \"\$(build-timestamp)\"|\$(preempt-flag-y) \"Thu Jul 11 07:05:47 UTC 2024\"|' ./common/init/Makefile
          
          # Remove check_defconfig
           sed -i 's/check_defconfig//' ./common/build.config.gki
           sed -i '$s|echo "\$res"|echo "\$res-RoksuðŸ’¢ðŸ’¢"|' ./common/scripts/setlocalversion
          
    - name: Build Kernel
      run: |
        cd /mnt/kernel_workspace
          rm -rf ./common/android/abi_gki_protected_exports_*
            sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
            tools/bazel build --config=fast --stamp //common:kernel_aarch64_dist
            cp ./bazel-bin/common/kernel_aarch64/Image $GITHUB_WORKSPACE/kernel_workspace/
            cp ./bazel-bin/common/kernel_aarch64/Image.lz4 $GITHUB_WORKSPACE/kernel_workspace/

    - name: Make Anykernel3
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/TheWildJames/AnyKernel3.git -b gki-2.0
        cp $GITHUB_WORKSPACE/kernel_workspace/Image AnyKernel3/Image
        
    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: kernel_workspace/Image

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AK3-${{ env.BUILD_TIME }}
        path: kernel_workspace/AnyKernel3/*
